<script>
    $(document).ready(function () {
        $('#tbp').DataTable({
            "oLanguage": {
                "sEmptyTable": "Nenhum registro encontrado",
                "sInfo": "Mostrando de _START_ at&eacute; _END_ de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando 0 at&eacute; 0 de 0 registros",
                "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                "sInfoPostFix": "",
                "sInfoThousands": ".",
                "sLengthMenu": "Exibir _MENU_ resultados por p&aacute;gina",
                "sLoadingRecords": "Carregando...",
                "sProcessing": "Processando...",
                "sZeroRecords": "Nenhum registro encontrado",
                "sSearch": "Pesquisar :",
                "oPaginate": {
                    "sNext": "Pr&oacute;ximo",
                    "sPrevious": "Anterior",
                    "sFirst": "Primeiro",
                    "sLast": "&Uacute;ltimo"
                },
                "oAria": {
                    "sSortAscending": ": Ordenar colunas de forma ascendente",
                    "sSortDescending": ": Ordenar colunas de forma descendente"
                }
            }
        });
    });
</script>
<h3>Principal</h3>
<form class="form" id="formPrincipal" method="POST" action="<?= $this->actionForm ?>">
    <div class="grid-12-12">
        <table id="tbp" class="display" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <td>N&uacute;mero</td>
                    <td>T&iacute;tulo<td>
                </tr>
            </thead>
            <tbody>
                <?php
                if (count($this->objConsulta)) {
                    foreach ($this->objConsulta as $values) {
                        echo "<tr>";
                        echo "<td>" . $values->getNumero() . "</td>";
                        echo "<td>" . $values->getTitulo() . "</td>";
                        echo "</tr>";
                    }
                }
                ?>
            <tbody>
        </table>
    </div>
</form>