<script>
jQuery(document).ready(function(){

	//jQuery("#dtVigencia").datepicker();
	
    jQuery('#frmPlanosSaude').validate({
        rules: {
		idTipoPlano: 	  {required: true},
		idOperadora: 	  {required: true},
		noCategoriaPlano: {required: true},
		idAcomodacao:	  {required: true},
		dsCategoriaPlano: {required: true},
		dsRedeCredenciada:{required: true},
		noFaixaEtaria0:   {required: true},
		nuValor0:		  {required: true},
		dtVigencia:		  {required: true}
	 	},
	 	messages: {
	 		idTipoPlano: 	  {required: 'Campo obrigatório'},
			idOperadora: 	  {required: 'Campo obrigatório'},
			noCategoriaPlano: {required: 'Campo obrigatório'},
			idAcomodacao:	  {required: 'Campo obrigatório'},
			dsCategoriaPlano: {required: 'Campo obrigatório'},
			dsRedeCredenciada:{required: 'Campo obrigatório'},
			noFaixaEtaria0:   {required: 'Campo obrigatório'},
			nuValor0:		  {required: 'Campo obrigatório'},
			dtVigencia:		  {required: 'Campo obrigatório'}
	    }
    });

    jQuery('#idOperadora').change(function(){
    	Funcoes.carregaCategoriaPlano('<?= $this->baseUrl() ?>/cadastro/combocategoria/','categoria',jQuery('#idOperadora').val());
    });

});
</script>
<h1>CADASTRAR PLANOS DE SAÚDE</h1>
<form class="form" id="frmPlanosSaude" method="POST" action="<?= $this->actionForm ?>">

    <fieldset>
        <legend>Dados do plano de saude</legend>
        <div class="grid-5-12">
            <label class="form-lbl">Tipo do plano:</label>
            <select id="idTipoPlano" name="idTipoPlano">
            	<option value="">Selecione...</option>
	            <?php if( count( $this->objTipoPlano ) ): ?>
		            <?php foreach( $this->objTipoPlano as $values ): ?>
		                <option value="<?= $values->getIdTipoPlano() ?>"><?= $values->getNoTipoPlano() ?></option>
		            <?php endforeach; ?>
	            <?php endif; ?>
            </select>
        </div>
        <div class="grid-7-12">
            <label class="form-lbl">Operadora:</label>
            <select id="idOperadora" name="idOperadora">
            	<option value="">Selecione...</option>
	            <?php if( count( $this->objOperadora ) ): ?>
		            <?php foreach( $this->objOperadora as $values ): ?>
		                <option value="<?= $values->getIdOperadora() ?>"><?= $values->getNoOperadora() ?></option>
		            <?php endforeach; ?>
	            <?php endif; ?>
            </select>
        </div>
        <div class="grid-12-12"></div>
        <div class="grid-5-12" id="categoria">
            <label class="form-lbl">Categoria:</label>
            <select id="idCategoriaPlano" name="idCategoriaPlano">
				<option value="">Selecione...</option>
			</select>
        </div>
        <div class="grid-7-12">
            <label class="form-lbl">Acomodação:</label>
            <select id="idAcomodacao" name="idAcomodacao">
            	<option value="">Selecione...</option>
	            <?php if( count( $this->objAcomodacao ) ): ?>
		            <?php foreach( $this->objAcomodacao as $values ): ?>
		                <option value="<?= $values->getIdAcomodacao() ?>"><?= $values->getNoAcomodacao() ?></option>
		            <?php endforeach; ?>
	            <?php endif; ?>
            </select>
        </div>
        <div class="grid-12-12"></div>
        <div class="grid-3-12">
        	<label class="form-lbl">Vigência dos valores:</label>
            <input type="text" class="form-txt" id="dtVigencia" name="dtVigencia" maxlength="10"></input>
        </div>
        <div id="faixa" class="grid-2-12">
            <label class="form-lbl">Faixa etária:</label>
            <input type="text" class="form-txt" id="noFaixaEtaria0" name="noFaixaEtaria0" maxlength="6"></input>
        </div>
        <div id="valor" class="grid-2-12">
            <label class="form-lbl">Valor:</label>
            <input type="text" class="form-txt" id="nuValor0" name="nuValor0" maxlength="9"></input>
        </div>
        <div class="grid-5-12 form-no-lbl">
        	<input type="hidden" name="cont" id="cont" value="0"/>
			<input class="form-button" type="button" value="Adicionar" title="Adicionar" onclick="addFormField();"/>
			<input class="form-button" type="button" value="Remover" title="Remover" onclick="removeFormField();">
    	</div>
    </fieldset>
	<div class="grid-4-12 form">
        <input class="form-button" id="btSalvar" type="submit" value="Salvar" title="Salvar"/>
    </div>
</form>