<script>
    $(document).ready(function(){
        //$("input:text").setMask();

	    $("#idTipoPlano").change(function(){
	    	Funcoes.carregaCategoriaPlano('<?= $this->baseUrl() ?>/conteudo/operadora/','plano',$('#idTipoPlano').val());
	    });

		$("#frmPessoais").validate({
			rules:{
				nuTelefone:{required: function(){if($('#nuCelular').val() == "" && $('#dsEmail').val() == ""){return true;}else{return false;}}},
				nuCelular:{required: function(){if($('#nuTelefone').val() == "" && $('#dsEmail').val() == ""){return true;}else{return false;}}},
				dsEmail:{required: function(){if($('#nuTelefone').val() == "" && $('#nuCelular').val() == ""){return true;}else{return false;}}}
			}
			,
			messages:{
				nuTelefone:"Telefone, ",
				nuCelular:"Celular ou",
				dsEmail:"Email"
			}
			,
			submitHandler: function(form) {
				var ok = true;
				/*if($('#nuTelefone').val() == "" && $('#nuCelular').val() == "" && $('#dsEmail').val() == ""){
					ok = false;
					$("#msgErro").text("Informe pelo menos um meio de contato.");
					$("#msgErro").show();
				}*/

				if(ok){
					jQuery("html").showLoading();
					//form.submit();
				}
			}
		});
		
    });
</script>
<h2>Formulário de contato</h2>
<form class="form" id="frmPessoais" method="POST" action="<?= $this->actionForm ?>">
	<br>
    <fieldset>
        <legend><h4>Dados Pessoais</h4></legend>
        <div class="grid-8-12">
            <label class="form-lbl">Nome:</label>
            <input class="form-txt required" id="noPessoa" name="noPessoa" maxlength="60" size="40" value=""/>
            <label class="error" for="noPessoa" generated="true" style="display:none;color:red;">Campo obrigatório</label>
        </div>
        <div class="grid-4-12">
            <label class="form-lbl"> Idade:</label>
            <input class="form-txt required" id="nrIdade" name="nrIdade" maxlength="3" size="5" value=""
            		onkeypress="return teclaNumerica(event);"/>
            <label class="error" for="nrIdade" generated="true" style="display:none;color:red;">Campo obrigatório</label>
        </div>
	</fieldset>
	<br>
    <fieldset>
        <legend><h4>Contatos</h4></legend>
        <div class="grid-4-12">
            <label class="form-lbl">Telefone:</label>
            <input class="form-txt" id="nuTelefone" name="nuTelefone" alt="(99)9999-9999" size="15" value=""/>
        </div>
        <div class="grid-4-12">
            <label class="form-lbl">Celular:</label>
            <input class="form-txt" id="nuCelular" name="nuCelular" alt="(99)9999-9999" size="15" value=""/>
        </div>
        <div class="grid-4-12"></div>
        <div class="grid-6-12">
            <label class="form-lbl">Email:</label>
            <input class="form-txt" id="dsEmail" name="dsEmail" maxlength="99" size="60" value=""/>
            <br>
            <label style="color:red;">Informe pelo menos uma forma de contato.</label>
			<label class="error" id="msgErro" for="nuTelefone" generated="true" style="display:none;color:red;">Telefone, </label>
			<label class="error" id="msgErro" for="nuCelular" generated="true" style="display:none;color:red;">Celular ou </label>
			<label class="error" id="msgErro" for="dsEmail" generated="true" style="display:none;color:red;">Email</label>
        </div>
    </fieldset>
    <br>
    <fieldset>
        <legend><h4>Informação / Sugestão</h4></legend>
        <div class="grid-12-12">
        	<textarea id="dsContato" class="required" name="dsContato" rows="10" cols="50" maxlength="400"></textarea>
        	<label class="error" for="dsContato" generated="true" style="display:none;color:red;">Campo obrigatório</label>
        </div>
    </fieldset>
    <div class="grid-4-12 form">
        <input class="form-button" type="submit" value="Enviar" title="Salvar" id="btSalvar"/>
    </div>
</form>