
<style type="text/css">
    a {
            color: #388398;
            text-decoration: none;
    }
    a:visited {
            color: #333300;
    }
    a:hover {
            color: #333300;
            text-decoration: underline;
    }
    h3 {
            margin: 0;
            padding: 0 0 .3em;
    }
    p {
            margin: 0;
            padding: 0 0 .5em;
    }
    .pane-list {
            margin: 0;
            padding: 0;
            list-style: none;
    }
    .pane-list li {
            background: #F5F5F5;
            padding: 10px 20px 10px;
            border-top: solid 1px #A7BECC;
            cursor: pointer;
    }
    .pane-list li:hover {
            background: #f6ffe9;
    }
</style>
<script>
jQuery(document).ready(function(){

	jQuery('#frmIndex').validate({
		rules: {
        	user: {required: true},
        	pswd: {required: true}
        },
        messages: {
           	user: 'Campo obrigatório',
           	pswd: 'Campo obrigatório'
        }
    });
});
</script>
<div id="conteudoTopo">
    <form class="form" id="frmIndex" method="POST" action="<?= $this->actionForm ?>">
    <div id="conteudoLeft">
        <div class="grid-12-12">
            <div class="grid-5-12"></div>
            <div class="grid-2-12">
                <fieldset>
                    <h3>Login</h3>
                    <h2><?php echo $this->message ?></h2>
                    <label class="form-lbl">Usu&aacute;rio:</label> 
                    <input type="text" class="textfield" name="user" style="width: 200px;" value=""><br>
                    <label  class="form-lbl">Senha:</label> 
                    <input type="password" class="textfield" name="pswd" style="width: 200px;" value=""><br>
                    <p></p>
                    <input type="submit" class="form-button" value="Acessar">
                </fieldset>
            </div>
            <div class="grid-5-12"></div>
        </div>    
    </div>
</form>
</div>
