<script>
jQuery('#frmPlanosSaude').ready(function(){
	jQuery('#idAcomodacao').change(function(){
		carregaConteudoPagina('<?= $this->baseUrl() ?>/conteudo/acomodacao/','valor','<?php echo $this->id;?>',jQuery('#idAcomodacao').val());
    });
});
</script>
<div class="grid-4-12">
	<label class="form-lbl">Acomoda&ccedil;&atilde;o:</label>
   	<select id="idAcomodacao" name="idAcomodacao" style="width:99%;">
		<option value="">Selecione...</option>
		<?php if( count( $this->objAcomodacao ) ):
			foreach( $this->objAcomodacao as $values ): ?>
				<option value="<?= $values->getIdAcomodacao() ?>"><?= $values->getNoAcomodacao() ?></option>
			<?php endforeach;
		endif; ?>
	</select>
</div>
<div id="valor" class="grid-8-12">
</div>
<div id="maisDetalhe1" class="grid-12-12">
<?php if( count( $this->objDescCategoria ) ): 
	foreach( $this->objDescCategoria as $value ): ?>
		<div class="grid-12-12">
			<label class="form-lbl">Descri&ccedil;&atilde;o do plano:</label>
			<textarea class="form-txt" id="dsCategoriaPlano" name="dsCategoriaPlano" readonly="readonly" maxlength="200" style="width: 99%;" rows="10"><?= $value->getDsCategoriaPlano() ?></textarea>
		</div>
		<div class="grid-12-12">
			<label class="form-lbl">Rede credenciada:</label>
			<textarea class="form-txt" id="dsRedeCredenciada" name="dsRedeCredenciada" readonly="readonly" maxlength="400" style="width: 99%;" rows="20"><?= $value->getDsRedeCredenciada() ?></textarea>
		</div>
	<?php endforeach; 
endif; ?>
</div>