<script>
jQuery('#frmPlanosSaude').ready(function(){
	jQuery('#idTipoPlano').change(function(){
		if(this.value == 1)
		{
			carregaConteudoPagina('<?= $this->baseUrl() ?>/conteudo/listacategoriaplano/','categoriaPlano',this.value,'<?php echo $this->idPlano;?>');
		}
		else if(this.value == 2)
		{
			carregaPagina('<?= $this->baseUrl() ?>/conteudo/avisoempresa','categoriaPlano',this.value);
		}
		else{
			jQuery('#categoriaPlano').html('');
			jQuery('#detalhe').html('');
		}
    });
});
</script>
<h1>Plano de Saúde</h1>
<form class="form" id="frmPlanosSaude" method="POST" action="<?= $this->actionForm ?>">
    <img src="../../../../img/img_logo/<?php echo $this->idPlano; ?>.jpg" width="150px" height="75px;"/>
    <fieldset style="border: 1px solid #cacaca;">
        <legend>Dados do plano de saude</legend>
        <div class="grid-5-12">
            <label class="form-lbl">Tipo do plano:</label>
            <select id="idTipoPlano" name="idTipoPlano" style="width:99%;">
            	<option value="">Selecione...</option>
	            <?php if( count( $this->objTipoPlano ) ): 
		            foreach( $this->objTipoPlano as $values ): ?>
		                <option value="<?= $values->getIdTipoPlano() ?>"><?= $values->getNoTipoPlano() ?></option>
		            <?php endforeach; 
	            endif; ?>
            </select>
        </div>
        <div id="categoriaPlano" class="grid-4-12"></div>
        <div id="detalhe" class="grid-12-12"></div>
    </fieldset>
</form>    