<html>
    <head>

        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>SISDOC</title>

        <link href="/css/reset.css" rel="stylesheet" type="text/css" />
        <link href="/css/style.css" rel="stylesheet" type="text/css" />
        <link href="/css/color1.css" rel="stylesheet" type="text/css" />
        <link href="/css/datePicker.css" rel="stylesheet" type="text/css" />
        <link href="/css/fx.slice.css" rel="stylesheet" type="text/css" />
        <link href="/scripts/newsslider/slider.css" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" href="/scripts/nivoslider/nivo-slider.css" type="text/css" media="screen" />
        <link rel="stylesheet" href="/css/formee/form-structure.css" type="text/css" media="screen" />
        <link rel="stylesheet" href="/css/formee/form-style.css" type="text/css" media="screen" />

        <script type="text/javascript" src="/js/jquery/jquery.js"></script>
        <script type="text/javascript" src="/js/jquery/jquery-latest.js"></script>

        <script type="text/javascript" src="/js/jquery/jquery.validate.js"></script>
        <script type="text/javascript" src="/js/funcoes_uteis.js"></script>    
        <script type="text/javascript" src="/js/jquery/jquery.ui.datepicker.js"></script>
        <script type="text/javascript" src="/js/jquery/jquery.ui.datepicker-pt-BR.js"></script>    
        <script type="text/javascript" src="/js/jquery/mootools-1.2-core-yc.js"></script>
        <script type="text/javascript" src="/js/jquery/mootools-1.2-more.js"></script>
        <script type="text/javascript" src="/js/jquery/fx.slice.js"></script> 

        <script type="text/javascript" src="/scripts/animate.js"></script> 
        <script type="text/javascript" src="/scripts/nivoslider/jquery.nivo.slider.pack.js"></script>
        <script type="text/javascript" src="/scripts/cufon/cufon-yui.js"></script>
        <script type="text/javascript" src="/scripts/jquery.corner.js"></script>
        <script type="text/javascript" src="/scripts/newsslider/slider.js"></script>

        <script type="text/javascript">
        jQuery.noConflict();
        jQuery(window).load(function () {
            jQuery('#slider').nivoSlider();
        });

        jQuery.noConflict();
        jQuery('.slider').corner("8px");


        </script>

    </head>
    <body>
        <!-- Login 
        <div id="login">
            <div class="loginContent">
                <form action="/" method="post">
                    <label for="user" style="padding-left: 25%;"><b>Username: </b></label>
                    <input class="field" type="text" name="user" id="user" value="" size="23" />
                    <label for="pwd"><b>Password:</b></label>
                    <input class="field" type="password" name="pwd" id="pwd" size="23" />
                    <input type="submit" name="submit" value="" class="button_login" />
                </form>
                <div class="left"></div>
                <div class="right"></div> 
            </div>
            <div class="loginClose"><a href="#" id="closeLogin">Close Panel</a></div>
        </div> 
        <div id="topLogin" style="background-color: black;">
            <ul class="login">
                <li class="left">&nbsp;</li>
                <li><label id="lblNoUser">Hello Guest! &nbsp;&nbsp;&nbsp;&nbsp;| </label></li>
                <li>
                    <a id="toggleLogout" href="/index/logout">Log Out</a>
                    <a id="toggleLogin" href="#">Log In</a>
                    <?php //if ($this->valid) { ?>
                        <script>
                            jQuery(function () {
                                jQuery("#lblNoUser").show();
                                jQuery("#toggleLogout").show();
                                jQuery("#toggleLogin").hide();
                            });
                        </script>
                    <?php //} else { ?>
                        <script>
                            jQuery(function () {
                                jQuery("#lblNoUser").hide();
                                jQuery("#toggleLogout").hide();
                                jQuery("#toggleLogin").show();
                            });
                        </script>
                    <?php //} ?>
                </li>
            </ul> 
        </div>
         / login -->
        <div id="top">
            <div id="logo"></div>
            <br style="clear:both" />		
        </div>
        <div id="menu-primary" class="menu-container">
            <div class="menu" style="padding-left:12%;">
                <ul id="menu-primary-items" class="sf-js-enabled" style="width:990px;">
                    <?php if ($this->valid) { ?>
                        <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-20"><a href="<?php echo $this->baseUrl() ?>/cadastro/operadora">Operadora</a></li>
                        <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-20"><a href="<?php echo $this->baseUrl() ?>/cadastro/categoriaplano">Categoria Plano</a></li>
                        <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-20"><a href="<?php echo $this->baseUrl() ?>/cadastro/cadastroplanos">Planos de saúde</a></li>
                        <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-20"><a href="<?php echo $this->baseUrl() ?>/alterar/alterarplanos">Alterar plano</a></li>
                        <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-20"><a href="<?php echo $this->baseUrl() ?>/conteudo/listapessoacontato">Lista Contatos</a></li>
                    <?php } ?>
                </ul>
            </div>
        </div>
        <div id="container">
            <div style="width:75%; float:left;clear:rigth;">
                <?php echo $this->layout()->content; ?>
            </div>          
            <div class="clean"></div>
            <div class="slider_shadow_bottom"></div>
        </div>
        <div class="clean"></div>
        <div id="footer">
            <div class="footer_container">
                <div class="left_column">
                    <h3 style="font-size: 13px;">Copyright <?= Date("Y");?></h3>
                </div>
                <div class="right_column">
                    <h3 style="font-size: 13px;">Murilo | Geovani</h3>
                </div>
                <div class="clean"></div>
            </div>
        </div>
    </body>
</html>
