<html>
<head>

<!-- Google Website Optimizer Control Script -->
<script>
	function utmx_section(){}function utmx(){}
	(function(){var k='1436381533',d=document,l=d.location,c=d.cookie;function f(n){
	if(c){var i=c.indexOf(n+'=');if(i>-1){var j=c.indexOf(';',i);return escape(c.substring(i+n.
	length+1,j<0?c.length:j))}}}var x=f('__utmx'),xx=f('__utmxx'),h=l.hash;
	d.write('<sc'+'ript src="'+
	'http'+(l.protocol=='https:'?'s://ssl':'://www')+'.google-analytics.com'
	+'/siteopt.js?v=1&utmxkey='+k+'&utmx='+(x?x:'')+'&utmxx='+(xx?xx:'')+'&utmxtime='
	+new Date().valueOf()+(h?'&utmxhash='+escape(h.substr(1)):'')+
	'" type="text/javascript" charset="utf-8"></sc'+'ript>')})();
</script>
<script>utmx("url",'A/B');</script>
<!-- End of Google Website Optimizer Control Script -->
<!-- Google Website Optimizer Tracking Script -->
<script type="text/javascript">
	var _gaq = _gaq || [];
	_gaq.push(['gwo._setAccount', 'UA-30856504-2']);
	_gaq.push(['gwo._trackPageview', '/1436381533/test']);
	(function() {
	var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	})();
</script>
<!-- End of Google Website Optimizer Tracking Script -->

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>4103-0261 :: INDICO SAÚDE</title>

    <link href="/css/reset.css" rel="stylesheet" type="text/css" />
    <link href="/css/style.css" rel="stylesheet" type="text/css" />
    <link href="/css/color1.css" rel="stylesheet" type="text/css" />
    <link href="/css/datePicker.css" rel="stylesheet" type="text/css" />
    <link href="/css/fx.slice.css" rel="stylesheet" type="text/css" />
    <link href="/scripts/newsslider/slider.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="/scripts/nivoslider/nivo-slider.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="/css/formee/form-structure.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="/css/formee/form-style.css" type="text/css" media="screen" />

    <script type="text/javascript" src="/js/jquery/jquery.js"></script>
    <script type="text/javascript" src="/js/jquery/jquery-latest.js"></script>

    <script type="text/javascript" src="/js/jquery/jquery.validate.js"></script>
    <script type="text/javascript" src="/js/funcoes_uteis.js"></script>    
    <script type="text/javascript" src="/js/jquery/jquery.ui.datepicker.js"></script>
    <script type="text/javascript" src="/js/jquery/jquery.ui.datepicker-pt-BR.js"></script>    
    <script type="text/javascript" src="/js/jquery/mootools-1.2-core-yc.js"></script>
    <script type="text/javascript" src="/js/jquery/mootools-1.2-more.js"></script>
    <script type="text/javascript" src="/js/jquery/fx.slice.js"></script> 
    
    <script type="text/javascript" src="/scripts/animate.js"></script> 
    <script type="text/javascript" src="/scripts/nivoslider/jquery.nivo.slider.pack.js"></script>
    <!-- <script type="text/javascript" src="/scripts/cufon/Diavlo_Book_400.font.js"></script> -->
    <script type="text/javascript" src="/scripts/cufon/cufon-yui.js"></script>
    <script type="text/javascript" src="/scripts/jquery.corner.js"></script>
    <script type="text/javascript" src="/scripts/newsslider/slider.js"></script>
   
    <script type="text/javascript">
        jQuery.noConflict();
        jQuery(window).load(function() {
            jQuery('#slider').nivoSlider();
        });

        jQuery.noConflict();
        jQuery('.slider').corner("8px");


    	//verifica se o IE é o 9, e solicita para habiliat o modo de compatibilidade
        if(navigator.appVersion.indexOf("MSIE")!= -1){
        	var temp = navigator.appVersion.split("MSIE");
        	var versao = parseFloat(temp[1]);
        	if(versao == 9){
        		alert("Voc"+String.fromCharCode(136)+" est"+String.fromCharCode(225)+" usando o Internet Explorer " + versao + ".\n\nPara uma melhor navegação utilize o Firefox ou Chrome.");
            }
        }

    	//dados google analytics    
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', 'UA-30856504-1']);
		_gaq.push(['_trackPageview']);
		
		(function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();
	</script>

    <!-- <script type="text/javascript">
        //Cufon.replace ('h1') ('h2') ('h3') ('h4') ('h5') ('h6') ('.menu',{hover:true});
    </script> -->

 
</head>
    <!-- <body onload="autoScroll('newsslider','newssection',5,true)"> -->
	<body>
		<!-- Login -->
		<div id="login">
			<div class="loginContent">
				<form action="/" method="post">
					<label for="user" style="padding-left: 25%;"><b>Username: </b></label>
					<input class="field" type="text" name="user" id="user" value="" size="23" />
					<label for="pwd"><b>Password:</b></label>
					<input class="field" type="password" name="pwd" id="pwd" size="23" />
					<input type="submit" name="submit" value="" class="button_login" />
				</form>
				<div class="left">
	            	<!-- <label for="rememberme"><input name="rememberme" id="rememberme" class="rememberme" type="checkbox" checked="checked" value="forever" /> Remember me</label> -->
	            </div>
				<div class="right"><!-- Not a member? <a href="#">Register</a> | <a href="#">Lost your password?</a> --></div> --
			</div>
			<div class="loginClose"><a href="#" id="closeLogin">Close Panel</a></div>
		</div> 
		<div id="topLogin" style="background-color: black;">
			<ul class="login">
		    	<li class="left">&nbsp;</li>
		        <li><label id="lblNoUser">Hello Guest! &nbsp;&nbsp;&nbsp;&nbsp;| </label></li>
				<li>
					<a id="toggleLogout" href="/index/logout">Log Out</a>
					<a id="toggleLogin" href="#">Log In</a>
					<?php if ($this->valid) { ?>
						<script>
						jQuery(function(){
							jQuery("#lblNoUser").show();
							jQuery("#toggleLogout").show();
							jQuery("#toggleLogin").hide();
						});
						</script>
					<?php }else{ ?>
						<script>
						jQuery(function(){
							jQuery("#lblNoUser").hide();							
							jQuery("#toggleLogout").hide();
							jQuery("#toggleLogin").show();
						});
						</script>
					<?php } ?>
				</li>
			</ul> 
		</div>
		<!-- / login -->
        <div id="top">
            <div id="logo"></div>
            <br style="clear:both" />		
        </div>
        <div id="menu-primary" class="menu-container">
                <div class="menu" style="padding-left:12%;">
                        <ul id="menu-primary-items" class="sf-js-enabled" style="width:990px;">
                                <!-- li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-20"><a target="_blank" href="http://blog.indicosaude.com.br">Blog</a></li -->
                                <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-20"><a href="/">Home</a></li>
                                <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-20"><a href="/contato/pessoal">Contatos</a></li>
                                <?php if ($this->valid) {?>
                                        <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-20"><a href="<?php echo $this->baseUrl() ?>/cadastro/operadora">Operadora</a></li>
                                        <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-20"><a href="<?php echo $this->baseUrl() ?>/cadastro/categoriaplano">Categoria Plano</a></li>
                                        <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-20"><a href="<?php echo $this->baseUrl() ?>/cadastro/cadastroplanos">Planos de saúde</a></li>
                                        <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-20"><a href="<?php echo $this->baseUrl() ?>/alterar/alterarplanos">Alterar plano</a></li>
                                        <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-20"><a href="<?php echo $this->baseUrl() ?>/conteudo/listapessoacontato">Lista Contatos</a></li>
                                <?php } ?>
                        </ul>
                </div>
        </div>
        <!-- end top -->
        <div class="slider_container">
            <div class="slider_shadow_top"></div>
            <div class="slider">
                <div id="slider">
                    <img src="/img/slides/1.jpg" alt="" title="Bradesco Saúde" width="950" height="276"/> 
                    <!-- img src="/img/slides/2.jpg" alt="" title="Golden Cross" width="950" height="276"/ -->
                    <img src="/img/slides/amil.jpg" alt="" title="AMIL" width="950" height="276"/>
                    <!-- img src="/img/slides/7.jpg" alt="" title="Unimed Centro-Oeste e Tocantins" width="950" height="276"/ --> 
                </div>
            </div>
            
        </div>
        <div id="container">
            <div style="width:75%; float:left;clear:rigth;">
            	<?php echo $this->layout()->content; ?>
            </div>
            <div class="news" style="width:23%;">
                    <div class="news_head">
                        <h2>CONTATOS</h2>
                    </div>
                    <div class="newsslider">
                        <div class="newsslidercontent" id="newsslider">
                            <div>
                                <div>
                                    <h3>PLANTÃO DE VENDAS <br> 4103-0261</h3>
                                </div>
                            </div>
                            <div id="newssection-1" class="newssection upper">
                                <!-- div class="news_date">ESCRITÓRIO<br /></div>
                                <div class="news_text">(61)3223-2925</div -->
                                
                                <div class="news_date">CLARO<br /></div>
                                <div class="news_text">(61)9304-3648</div>
                                
                                <div class="news_date">OI<br /></div>                                
                                <div class="news_text">(61)8626-0601</div>
                                
                                <div class="news_date">TIM<br /></div>                                
                                <div class="news_text">(61)8229-4177</div>
                                
                                <div class="news_date">VIVO<br /></div>                                
                                <div class="news_text">(61)9824-0601</div>
                                
                                <div class="news_date">
                                    <br />
                                    <a href="mailto:contato@indicosaude.com.br">contato@indicosaude.com.br</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div>
                        <a href="#" onclick="window.open('http://indicosaude.com.br/online/chat.php?code=U0VSVkVSUEFHRQ__','','width=590,height=725,left=0,top=0,resizable=yes,menubar=no,location=yes,status=yes,scrollbars=yes')">
                            <img alt="Atendimento online" src="http://indicosaude.com.br/online/banner/livezilla_03_0.jpg">
                        </a>
                    </div>
                    <div>
			   <br/>
			   <h4>A partir de R$ 19,80 (Servidor p&uacute;blico)</h4>
                        <img alt="Plano dental" src="/img/prodent.jpg">
                    </div>
                </div>
        <!-- end container -->
        <div class="clean"></div>
        <div class="slider_shadow_bottom"></div>
        
        <!-- end services -->
        <!-- end content -->
        </div>
        <div class="clean"></div>
        <div id="footer">
            <div class="footer_container">
                <div class="left_column">
                    <h3 style="font-size: 13px;">INDICO SAÚDE ® - Copyright 2012</h3>
                </div>
                <div class="right_column">
                    <h3 style="font-size: 13px;">André Luiz Geraldi | Geovani Geraldi</h3>
                </div>
                <div class="clean"></div>
            </div>
            <!-- end footer_container -->
        </div>
        <!-- end footer -->
    </body>
</html>
