<span class="preload1"></span>
<span class="preload2"></span>

<ul id="nav">
    <li class="top"><a href="<?= $this->baseUrl() ?>/" class="top_link"><span>Home</span></a></li>
    <li class="top"><a href="#" id="shop" class="top_link"><span class="down">Cadastro</span></a>
        <ul class="sub">
        	<li><a href="<?= $this->baseUrl() ?>/cadastro/categoriaplano">Categoria Plano</a></li>
        	<li><a href="<?= $this->baseUrl() ?>/cadastro/operadora">Operadora</a></li>
            <li><a href="<?= $this->baseUrl() ?>/cadastro/pessoal">Pessoa</a></li>
            <li><a href="<?= $this->baseUrl() ?>/cadastro/cadastroplanos">Planos de saúde</a></li>
        </ul>
    </li>
    <li class="top"><a href="<?= $this->baseUrl() ?>/contato" id="privacy" class="top_link"><span>Contato</span></a></li>
</ul>